Task 1
aziza-calm/2019-2-Track-Frontend-A-Kalmasova pull request #1
Opened 2019-10-15 06:40 UTC by aziza-calm

# Домашнее задание № 1

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
*
*
*

2019-10-15 08:59 UTC, chexex reviewed
Пробуем исправления, если без ошибок, то мержим

2019-10-15 08:59 UTC, chexex commented on package.json
> +    "2": "^2.0.0",
что-то здесь не так :)

2019-10-15 08:59 UTC, chexex commented on package.json
> +    "test": "CI=true",
```suggestion
    "test": "CI=true npm run test:engine && npm run test:unit && npm run lint",
```

2019-10-15 20:20 UTC, martinkomitsky commented on package.json
> +    "2": "^2.0.0",
Diese Nummer muss gelöscht werden

2019-10-16 03:51 UTC, martinkomitsky commented
@chexex нисобираеццо(

2019-10-16 10:49 UTC, aziza-calm commented
The command "npm run build" exited with 0.
Но eslint всячески ругается :(

npm i все время хочет каких-то зависимостей, которые должны быть установлены ручками. Он их почему-то хочет, даже если я уже установила отдельно

![Selection_044](https://user-images.githubusercontent.com/38079432/66912509-61606000-f01b-11e9-951f-aa6206df861a.png)

2019-10-16 16:24 UTC, chexex requested changes
Выполнить указания из комментов
Избавиться от странных файлов `=4.1.0` `=5.16.0`

2019-10-16 16:24 UTC, chexex commented on package.json
>  }
Замени содержимое своего package.json этим:
```
{
  "name": "2019-2-Track-Frontend-A-Kalmasova",
  "homepage": "aziza-calm.github.io/2019-2-Track-Frontend-A-Kalmasova/",
  "description": "Mail.Ru Group Frontend Track course, 2019",
  "version": "0.1.0",
  "author": "A Opalev",
  "dependencies": {
    "@emotion/core": "^10.0.14",
    "@emotion/styled": "^10.0.14",
    "babel-core": "^6.26.3",
    "babel-preset-stage-0": "^6.24.1",
    "cross-env": "^5.2.0",
    "dotenv": "^8.0.0",
    "node-sass": "^4.12.0",
    "normalize.css": "^8.0.1",
    "postcss": "^7.0.17",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-redux": "^7.1.0",
    "react-router-dom": "^5.0.1",
    "react-scripts": "^3.0.1",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.2",
    "redux-thunk": "^2.3.0",
    "sass-loader": "^7.1.0"
  },
  "devDependencies": {
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-react": "^7.0.0",
    "@wemake-services/eslint-config-javascript": "^0.3.0",
    "@wemake-services/eslint-config-jest": "^0.1.5",
    "@wemake-services/eslint-config-jsdoc": "^0.3.0",
    "@wemake-services/stylelint-config-scss": "^0.1.4",
    "babel-plugin-lodash": "^3.3.4",
    "babel-plugin-styled-components": "^1.10.6",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "check-engine": "^1.8.0",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-babel": "^5.3.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-react": "^7.4.0",
    "gh-pages": "^2.1.1",
    "husky": "^0.14.3",
    "jest": "^24.8.0",
    "jest-transform-stub": "^2.0.0",
    "jscpd": "^2.0.15",
    "prettier": "^1.14.2",
    "pretty-quick": "^1.6.0",
    "remark-cli": "^6.0.1",
    "remark-lint": "^6.0.5",
    "remark-preset-lint-markdown-style-guide": "^2.1.3",
    "rosie": "^2.0.1",
    "stylelint": "^9.10.1",
    "stylelint-a11y": "^1.2.0",
    "stylelint-config-css-modules": "^1.4.0",
    "stylelint-no-unsupported-browser-features": "^3.0.2",
    "stylelint-webpack-plugin": "^0.10.5"
  },
  "browserslist": [
    "> 5%",
    "last 2 versions",
    "not ie < 11",
    "not ie_mob < 11",
    "not dead"
  ],
  "scripts": {
    "predeploy": "npm run build",
    "deploy": "gh-pages -d build",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "eject": "react-scripts eject",
    "format": "prettier --write '**/*.{js,jsx,json,md}'",
    "format:changed": "pretty-quick",
    "format:staged": "pretty-quick --staged",
    "eslint-check": "eslint --print-config .eslintrc.js | eslint-config-prettier-check",
    "lint": "npm run lint:js && npm run lint:dup && npm run lint:css",
    "lint-fix": "eslint --fix",
    "clean": "rm -rf dist",
    "test": "CI=true npm run test:engine && npm run test:unit && npm run lint",
    "test:engine": "check-engine",
    "test:sec": "npm audit || true",
    "test:unit": "cross-env NODE_ENV=test jest",
    "lint:js": "eslint src/**/*.js",
    "lint:css": "stylelint 'client/**/*.{scss,css}' && stylelint --rd 'client/**/*.{scss,css}'",
    "lint:dup": "jscpd -g --threshold=1 client tests docker",
    "ci": "npm run test && npm run build && npm run test:sec"
  },
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged"
    }
  },
  "engines": {
    "npm": ">=6",
    "node": ">=8"
  }
}
```

2019-10-16 16:25 UTC, chexex commented
и еще package-lock.json удали, пожалуйста

2019-10-16 19:30 UTC, aziza-calm commented on package.json
>  }
не помогло :(

2019-10-18 12:08 UTC, aziza-calm commented
eeeeeeee он зеленый! ура!

2019-10-21 08:30 UTC, chexex commented
Функции +
Тесты +
Сборка +

Спасибо за работу,
10 баллов

2019-10-21 08:31 UTC, chexex approved these changes

2019-10-21 08:31 UTC, merged